/// Flutter icons CustomeIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomeIcons
///      fonts:
///       - asset: fonts/CustomeIcons.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomeIcons {
  CustomeIcons._();

  static const _kFontFam = 'CustomeIcons';
  static const String? _kFontPkg = null;

  static const IconData comment =
      IconData(0xf4ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
